language: java
services:
  - mysql
before_install:
  - mysql -e 'USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n'
  - mysql -u root --default-character-set=utf8 < ddl/ddl.sql